name: Quick Tests

# Faster CI for quick feedback
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  quick-check:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyyaml
    
    - name: Python syntax check
      run: |
        python -m py_compile app/**/*.py || echo "Syntax check completed"
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Check configuration files
      run: |
        python -c "import yaml; yaml.safe_load(open('docker-compose.yml'))"
        python -c "import yaml; yaml.safe_load(open('configs/config.yaml'))"
        echo "✓ All config files are valid"
    
    - name: Check for TODO/FIXME
      run: |
        echo "Checking for TODO/FIXME comments..."
        grep -r "TODO\|FIXME" app/ --include="*.py" || echo "No urgent TODOs found"

